export const mockFirebaseRecords = [
  {
    createdBy: null,
    creationDate: 1637883802524,
    currentOwner: "B9iucUbkz7uWut24Ryo0OlDW5Rry",
    description: "",
    groupId: "",
    id: "Cancel_1vkei",
    isSample: false,
    lastModified: 1637883805567,
    lastModifiedBy: null,
    modificationDate: 1637883805567,
    name: "updated_rule_2",
    objectType: "rule",
    pairs: [
      {
        id: "j23ip",
        source: {
          filters: {},
          key: "Url",
          operator: "Contains",
          value: "trytyut",
        },
      },
    ],
    ruleType: "Cancel",
    status: "Active",
  },
  {
    createdBy: "7px5zooOVjOHfAyGFMetTrrrzsg1",
    creationDate: 1638991081406,
    currentOwner: "7px5zooOVjOHfAyGFMetTrrrzsg1",
    description: "",
    groupId: "",
    id: "Redirect_xg1sm",
    isSample: false,
    lastModified: 1638997017360,
    lastModifiedBy: "7px5zooOVjOHfAyGFMetTrrrzsg1",
    modificationDate: 1638997017359,
    name: "Redirect to mock",
    objectType: "rule",
    pairs: [
      {
        destination: "https://beta.requestly.io/mock/ELkVSLIqVL09rK4EfT4w",
        id: "tala2",
        source: {
          filters: {},
          key: "Url",
          operator: "Contains",
          value: "facebook.com",
        },
      },
    ],
    ruleType: "Redirect",
    status: "Active",
  },
  {
    createdBy: "7px5zooOVjOHfAyGFMetTrrrzsg1",
    creationDate: 1638380143256,
    currentOwner: "7px5zooOVjOHfAyGFMetTrrrzsg1",
    description: "",
    groupId: "",
    id: "Cancel_6hzxi",
    isSample: false,
    lastModified: 1638380982944,
    lastModifiedBy: "7px5zooOVjOHfAyGFMetTrrrzsg1",
    modificationDate: 1638380157968,
    name: "Cancel FB",
    objectType: "rule",
    pairs: [
      {
        id: "734n9",
        source: {
          filters: {},
          key: "Url",
          operator: "Contains",
          value: "facebook",
        },
      },
    ],
    ruleType: "Cancel",
    status: "Inactive",
  },
  {
    createdBy: "7px5zooOVjOHfAyGFMetTrrrzsg1",
    creationDate: 1638373682533,
    currentOwner: "7px5zooOVjOHfAyGFMetTrrrzsg1",
    description: "",
    id: "Group_de6vs",
    lastModified: 1638381748313,
    lastModifiedBy: "7px5zooOVjOHfAyGFMetTrrrzsg1",
    name: "New Demo Group",
    objectType: "group",
    status: "Inactive",
  },
];
