export const BILLING_TEAM_NUDGE = {
  BILLING_TEAM_NUDGE_VIEWED: "BILLING_TEAM_NUDGE_VIEWED",
  BILLING_TEAM_NUDGE_CLOSED: "BILLING_TEAM_NUDGE_CLOSED",
  BILLING_TEAM_NUDGE_REQUEST_SENT: "BILLING_TEAM_NUDGE_REQUEST_SENT",
  BILLING_TEAM_NUDGE_REQUEST_FAILED: "BILLING_TEAM_NUDGE_REQUEST_FAILED",
  CHECKOUT_BILLING_TEAM_NUDGE_CLICKED: "CHECKOUT_BILLING_TEAM_NUDGE_CLICKED",
};
