import React, { useCallback, useState } from "react";
import { KeyValuePair } from "features/apiClient/types";
import { useQueryParamStore } from "features/apiClient/hooks/useQueryParamStore";
import { useAutogenerateStore } from "features/apiClient/hooks/useAutogenerateStore";
import { useScopedVariables } from "features/apiClient/helpers/variableResolver/variable-resolver";
import { KeyValueTable } from "../KeyValueTable/KeyValueTable";
import { AutoGeneratedTable } from "../KeyValueTable/AutoGeneratedTable";

interface QueryParamsTableProps {
  recordId: string;
  onQueryParamsChange: (queryParams: KeyValuePair[]) => void;
  children?: React.ReactNode;
}

function Data(props: {
  recordId: string;
  queryParams: KeyValuePair[];
  handleUpdateQueryParams: (updatedPairs: KeyValuePair[]) => void;
  children?: React.ReactNode;
}) {
  const scopedVariables = useScopedVariables(props.recordId);
  const [showDescription, setShowDescription] = useState(false);

  return (
    <KeyValueTable
      data={props.queryParams}
      variables={scopedVariables}
      onChange={props.handleUpdateQueryParams}
      extraColumns={{
        description: {
          visible: showDescription ?? false,
          onToggle: (show: any) => {
            setShowDescription(show);
          },
        },
        dataType: { visible: true },
      }}
      children={props.children}
      useStore={useQueryParamStore}
    />
  );
}

export const QueryParamsTable: React.FC<QueryParamsTableProps> = React.memo(
  ({ recordId, onQueryParamsChange, children }) => {
    const [queryParams, setQueryParams] = useQueryParamStore((state) => [state.queryParams, state.setQueryParams]);
    const [getAllQueryParams] = useAutogenerateStore((s) => [s.getAllQueryParams]);

    const autogeneratedQueryParams = getAllQueryParams();
    const handleUpdateQueryParams = useCallback(
      (updatedPairs: KeyValuePair[]) => {
        setQueryParams(updatedPairs);
        onQueryParamsChange(updatedPairs);
      },
      [onQueryParamsChange, setQueryParams]
    );

    return (
      <div className="table-container">
        {autogeneratedQueryParams.length > 0 && (
          <AutoGeneratedTable data={autogeneratedQueryParams} type="queryParams" />
        )}
        <div className="table-content">
          <Data
            queryParams={queryParams}
            recordId={recordId}
            handleUpdateQueryParams={handleUpdateQueryParams}
            children={children}
          />
        </div>
      </div>
    );
  }
);
