import React, { useCallback } from "react";
import { KeyValuePair } from "features/apiClient/types";
import { useQueryParamStore } from "features/apiClient/hooks/useQueryParamStore";
import { useAutogenerateStore } from "features/apiClient/hooks/useAutogenerateStore";
import { useScopedVariables } from "features/apiClient/helpers/variableResolver/variable-resolver";
import { KeyValueTable } from "../KeyValueTable/KeyValueTable";
import { AutoGeneratedTable } from "../KeyValueTable/AutoGeneratedTable";

interface QueryParamsTableProps {
  recordId: string;
  onQueryParamsChange: (queryParams: KeyValuePair[]) => void;
  bulkEditConfigs: {
    setIsBulkEditPanelOpen?: (isOpen: boolean) => void;
    setBulkEditTableType?: (type: "headers" | "queryParams") => void;
    showDescription?: boolean;
    onShowDescriptionChange?: (show: boolean) => void;
  };
}

function Data(props: {
  recordId: string;
  queryParams: KeyValuePair[];
  handleUpdateQueryParams: (updatedPairs: KeyValuePair[]) => void;
  setIsBulkEditPanelOpen?: (isOpen: boolean) => void;
  setBulkEditTableType?: (type: "headers" | "queryParams") => void;
  showDescription?: boolean;
  onShowDescriptionChange?: (show: boolean) => void;
}) {
  const scopedVariables = useScopedVariables(props.recordId);
  return (
    <KeyValueTable
      data={props.queryParams}
      variables={scopedVariables}
      onChange={props.handleUpdateQueryParams}
      extraColumns={{
        description: {
          visible: props.showDescription ?? false,
          onToggle: (show: any) => {
            props.onShowDescriptionChange?.(show);
          },
        },
        dataType: { visible: true },
      }}
      config={{
        bulkEdit: {
          setIsBulkEditPanelOpen: props.setIsBulkEditPanelOpen,
          setBulkEditTableType: props.setBulkEditTableType,
          bulkEditTableType: "queryParams",
        },
      }}
    />
  );
}

export const QueryParamsTable: React.FC<QueryParamsTableProps> = React.memo(
  ({
    recordId,
    onQueryParamsChange,
    bulkEditConfigs: { setIsBulkEditPanelOpen, setBulkEditTableType, showDescription, onShowDescriptionChange },
  }) => {
    const [queryParams, setQueryParams] = useQueryParamStore((state) => [state.queryParams, state.setQueryParams]);
    const [getAllQueryParams] = useAutogenerateStore((s) => [s.getAllQueryParams]);

    const autogeneratedQueryParams = getAllQueryParams();
    const handleUpdateQueryParams = useCallback(
      (updatedPairs: KeyValuePair[]) => {
        setQueryParams(updatedPairs);
        onQueryParamsChange(updatedPairs);
      },
      [onQueryParamsChange, setQueryParams]
    );

    return (
      <div>
        {autogeneratedQueryParams.length > 0 && (
          <AutoGeneratedTable data={autogeneratedQueryParams} type="queryParams" />
        )}
        <Data
          queryParams={queryParams}
          recordId={recordId}
          handleUpdateQueryParams={handleUpdateQueryParams}
          setIsBulkEditPanelOpen={setIsBulkEditPanelOpen}
          setBulkEditTableType={setBulkEditTableType}
          showDescription={showDescription}
          onShowDescriptionChange={onShowDescriptionChange}
        />
      </div>
    );
  }
);
