import { useContext } from "react";
import { useStore } from "zustand";
import { useShallow } from "zustand/shallow";
import { AutogeneratedFieldsStore } from "../store/autogenerateStore";
import { AutogenerateStoreContext } from "../store/autogenerateContextProvider";

export function useAutogenerateStore<T>(selector: (state: AutogeneratedFieldsStore) => T) {
  const store = useContext(AutogenerateStoreContext);

  if (!store) {
    throw new Error("useautogenerateStore must be used within AutogenerateProvider");
  }

  return useStore(store, useShallow(selector));
}
