import { fetchGraphQLIntrospectionData } from "../helpers/introspectionQuery";
import { useSelector } from "react-redux";
import { getAppMode } from "store/selectors";
import { renderVariables } from "backend/environment/utils";
import { useAutogenerateStore } from "./useAutogenerateStore";
import { useGraphQLRecordStore } from "./useGraphQLRecordStore";
import { useApiClientFeatureContext } from "../slices";

export const useGraphQLIntrospection = (params: { recordId: string; url: string | undefined }) => {
  const [
    setIntrospectionData,
    setIsFetchingIntrospectionData,
    setHasIntrospectionFailed,
  ] = useGraphQLRecordStore((state) => [
    state.setIntrospectionData,
    state.setIsFetchingIntrospectionData,
    state.setHasIntrospectionFailed,
  ]);
  const appMode = useSelector(getAppMode);
  const ctx = useApiClientFeatureContext();
  const [getAllAutogeneratedHeaders, getAllAutogeneratedQueryParams] = useAutogenerateStore((state) => [
    state.getAllHeaders,
    state.getAllQueryParams,
  ]);

  const introspectAndSaveSchema = async () => {
    setIsFetchingIntrospectionData(true);
    try {
      const { result: renderedUrl } = renderVariables(params.url || "", params.recordId, ctx);
      const introspectionData = await fetchGraphQLIntrospectionData(
        renderedUrl,
        appMode,
        getAllAutogeneratedHeaders(),
        getAllAutogeneratedQueryParams()
      );
      if (!introspectionData) {
        throw new Error("No introspection data received");
      }
      setIntrospectionData(introspectionData);
      setHasIntrospectionFailed(false);
    } catch (error) {
      setIntrospectionData(null);
      setHasIntrospectionFailed(true);
    } finally {
      setIsFetchingIntrospectionData(false);
    }
  };

  return {
    introspectAndSaveSchema,
  };
};
