import React, { useCallback } from "react";
import { EnvironmentVariables } from "backend/environment/types";
import { KeyValuePair } from "features/apiClient/types";
import { KeyValueTable } from "../../../KeyValueTable/KeyValueTable";
import { useQueryParamStore } from "features/apiClient/hooks/useQueryParamStore";
import { useGenericState } from "hooks/useGenericState";
import { useAutogenerateStore } from "features/apiClient/hooks/useAutogenerateStore";

interface QueryParamsTableProps {
  variables: EnvironmentVariables;
}

export const QueryParamsTable: React.FC<QueryParamsTableProps> = ({ variables }) => {
  const { setUnsaved } = useGenericState();

  const [queryParams, setQueryParams] = useQueryParamStore((state) => [state.queryParams, state.setQueryParams]);
  const [_v, getAllQueryParams] = useAutogenerateStore((s) => [s.queryParamsVersion, s.getAllQueryParams]);

  const autogeneratedQueryParams = getAllQueryParams();

  console.log("DBG-1", _v, autogeneratedQueryParams);
  const handleUpdateQueryParams = useCallback(
    (updatedPairs: KeyValuePair[]) => {
      setQueryParams(updatedPairs);
      setUnsaved(true);
    },
    [setQueryParams, setUnsaved]
  );

  return <KeyValueTable data={queryParams} variables={variables} onChange={handleUpdateQueryParams} />;
};
