import React, { useCallback } from "react";
import { KeyValuePair, RQAPI } from "features/apiClient/types";
import { KeyValueTable } from "../../../KeyValueTable/KeyValueTable";
import { useQueryParamStore } from "features/apiClient/hooks/useQueryParamStore";
import { useAutogenerateStore } from "features/apiClient/hooks/useAutogenerateStore";
import { AutoGeneratedTable } from "../../../KeyValueTable/AutoGeneratedTable";
import { useScopedVariables } from "features/apiClient/helpers/variableResolver/variable-resolver";

interface QueryParamsTableProps {
  recordId: string;
  setRequestEntry: (updaterFn: (prev: RQAPI.Entry) => RQAPI.Entry) => void;
}

function Data(props: {
  recordId: string;
  queryParams: KeyValuePair[];
  handleUpdateQueryParams: (updatedPairs: KeyValuePair[]) => void;
}) {
  const scopedVariables = useScopedVariables(props.recordId);
  return (
    <KeyValueTable data={props.queryParams} variables={scopedVariables} onChange={props.handleUpdateQueryParams} />
  );
}

export const QueryParamsTable: React.FC<QueryParamsTableProps> = React.memo(({ recordId, setRequestEntry }) => {
  const [queryParams, setQueryParams] = useQueryParamStore((state) => [state.queryParams, state.setQueryParams]);
  const [_, getAllQueryParams] = useAutogenerateStore((s) => [s.queryParamsVersion, s.getAllQueryParams]);

  const autogeneratedQueryParams = getAllQueryParams();
  const handleUpdateQueryParams = useCallback(
    (updatedPairs: KeyValuePair[]) => {
      setQueryParams(updatedPairs);
      setRequestEntry((prev) => ({
        ...prev,
        request: {
          ...prev.request,
          queryParams: updatedPairs,
        },
      }));
    },
    [setQueryParams, setRequestEntry]
  );

  return (
    <div>
      {autogeneratedQueryParams.length > 0 && <AutoGeneratedTable data={autogeneratedQueryParams} type="queryParams" />}
      <Data queryParams={queryParams} recordId={recordId} handleUpdateQueryParams={handleUpdateQueryParams} />
    </div>
  );
});
