const REQUEST_METHOD_COLORS = {
  GET: "#00C8AF",
  POST: "#1E69FF",
  PUT: "#FF6905",
  DELETE: "#FC6675",
  PATCH: "#FFCA5F",
  HEAD: "#BEAAFF",
  OPTIONS: "#57BEE6",
};

export default REQUEST_METHOD_COLORS;
