import { createContext, ReactNode, useContext, useState } from "react";
import { StoreApi } from "zustand";
import { AutogeneratedFieldsStore, createAutogeneratedStore } from "./autogenerateStore";
import { NativeError } from "errors/NativeError";

export const AutogenerateStoreContext = createContext<StoreApi<AutogeneratedFieldsStore> | null>(null);

export const AutogenerateProvider = ({ children }: { children: ReactNode }) => {
  const [store] = useState(() => createAutogeneratedStore());
  return <AutogenerateStoreContext.Provider value={store}>{children}</AutogenerateStoreContext.Provider>;
};

export const useAutogenerateStoreContext = () => {
  const store = useContext(AutogenerateStoreContext);

  if (store === null) {
    throw new NativeError("useAutogenerateStoreContext must be used within AutogenerateProvider");
  }

  return store;
};
