import { createContext, ReactNode, useState } from "react";
import { StoreApi } from "zustand";
import { AutogeneratedFieldsStore, createAutogeneratedStore } from "./autogenerateStore";
import { RQAPI } from "../types";

export const AutogenerateStoreContext = createContext<StoreApi<AutogeneratedFieldsStore>>(null);

export const AutogenerateProvider = ({ children, entry }: { children: ReactNode; entry: RQAPI.Entry }) => {
  const [store] = useState(() => createAutogeneratedStore(entry));
  return <AutogenerateStoreContext.Provider value={store}>{children}</AutogenerateStoreContext.Provider>;
};
