import React, { useCallback, useMemo, useState } from "react";
import { KeyValuePair } from "features/apiClient/types";
import { useAutogenerateStore } from "features/apiClient/hooks/useAutogenerateStore";
import { useScopedVariables } from "features/apiClient/helpers/variableResolver/variable-resolver";
import { KeyValueTable } from "../KeyValueTable/KeyValueTable";
import { AutoGeneratedTable } from "../KeyValueTable/AutoGeneratedTable";
import { useHeadersStore } from "features/apiClient/hooks/useHeadersStore";

interface HeadersTableProps {
  headers: KeyValuePair[];
  recordId: string;
  onHeadersChange: (headers: KeyValuePair[]) => void;
}

function Data(props: {
  recordId: string;
  headers: KeyValuePair[];
  handleHeadersChange: (updatedPairs: KeyValuePair[]) => void;
}) {
  const scopedVariables = useScopedVariables(props.recordId);
  const [showDescription, setShowDescription] = useState(false);

  return (
    <KeyValueTable
      data={props.headers}
      variables={scopedVariables}
      onChange={props.handleHeadersChange}
      config={{
        checkInvalidCharacter: true,
      }}
      extraColumns={{
        description: {
          visible: showDescription,
          onToggle: (show: any) => {
            setShowDescription(show);
          },
        },
        dataType: { visible: true },
      }}
      useStore={useHeadersStore}
    />
  );
}

export const HeadersTable: React.FC<HeadersTableProps> = ({ recordId, onHeadersChange }) => {
  const [getAllHeaders] = useAutogenerateStore((s) => [s.getAllHeaders]);
  const storeHeaders = useHeadersStore((state) => state.headers);
  const setStoreHeaders = useHeadersStore((state) => state.setHeaders);

  const autogeneratedHeaders = useMemo(() => getAllHeaders(), [getAllHeaders]);

  const handleHeadersChange = useCallback(
    (updatedHeaders: KeyValuePair[]) => {
      setStoreHeaders(updatedHeaders);
      onHeadersChange(updatedHeaders);
    },
    [onHeadersChange, setStoreHeaders]
  );

  return (
    <div className="table-container">
      {autogeneratedHeaders.length > 0 && <AutoGeneratedTable data={autogeneratedHeaders} type="headers" />}
      <div className="table-content">
        <Data headers={storeHeaders} recordId={recordId} handleHeadersChange={handleHeadersChange} />
      </div>
    </div>
  );
};
