export const GA_EVENTS = {
  CATEGORIES: {
    RULES: "rules",
    RULE: "rule",
    GROUP: "group",
    USER: "user",
    SHARED_LIST: "shared list",
    TRASH: "trash",
    RULE_LOGS: "rule logs",
    EXTENSION: "extension",
    IN_APP_NOTIFICATION: "InAppNotification",
    NEED_HELP_FEATURE: "need help feature",
    PRICING: "pricing",
    LICENSE: "license",
    LIBRARY: "library",
    UNLOCK: "unlock",
    SPONSOR_SIDERAIL: "sponsor_siderail",
    LOGIN: "login",
    SIGNUP: "signup",
    REFERRAL: "referral",
    PAGE_VISITS: "page visits",
    REQUEST_UPGRADE: "request upgrade",
    MARKETPLACE: "marketplace",
    CHECKOUT: "checkout page",
    TEAMS: "teams page",
    ONBOARDING: "onboarding page",
    RULE_PAIRS: "rule pairs",
    DESKTOP_APP: "desktop app",
  },
  ACTIONS: {
    MODIFIED: "modified",
    CREATED: "created",
    DELETED: "deleted",
    ACTIVATED: "activated",
    DEACTIVATED: "deactivated",
    IMPORTED: "imported",
    EXPORTED: "exported",
    LIMIT_REACHED: "limit reached",
    AUTHENTICATED: "authenticated",
    VIEWED: "viewed",
    CLICKED: "clicked",
    COPIED: "duplicated",
    MARKED_FAVOURITE: "marked favourite",
    UNMARKED_FAVOURITE: "unmarked favourite",
    WORKFLOW_STARTED: "workflow started",
    ALREADY_LOGIN: "already login",
    LOGIN_REQUESTED: "login requested",
    LOGIN_DONE: "login done",
    LOGIN_REJECTED: "login rejected",
    FORM_SUBMITTED: "form submitted",
    FORM_REJECTED: "form rejected",
    INVALID_SUBMIT: "invalid submit",
    GROUPED: "grouped",
    UNGROUPED: "ungrouped",
    SHARED: "shared",
    ERROR: "error occured",
    TASK_COMPLETED: "task completed",
    BACKUP_CREATED: "backup created",
    BACKUP_USED: "backup used",

    CARD_ERROR: "card error",
    CARD_ACCEPTED: "card accepted",
    CARD_ENTERED: "card num and cv entered",

    CURRENCY_CHANGE: "currency_changed",
    DURATION_CHANGE: "duration_changed",
    APPLIED_SUCCESSFULLY: "applied_successfully",
    APPLIED_UNSUCCESSFULLY: "applied_unsuccessfully",

    REVOKED: "revoked",
    BOUGHT: "bought",
    UPDATED: "updated",
    REQUEST_ADMIN: "enterprise_plan_requested",

    UNINSTALLED: "uninstalled",
    UNINSTALL_RESPONSE: "uninstall_response",

    ROUTE_VIEWED: "route_viewed",
    EMAIL_LOGIN_PERFORMED: "email_login_performed",
    EMAIL_SIGNUP_PERFORMED: "email_signup_performed",
    GMAIL_LOGIN_PERFORMED: "gmail_login_performed",
    GMAIL_SIGNUP_PERFORMED: "gmail_signup_performed",
    MICROSOFT_LOGIN_PERFORMED: "microsoft_login_performed",
    APPLE_LOGIN_PERFORMED: "apple_login_performed",

    REFERRAL_APPLIED: "referral_applied",
    REFERRAL_FAILED: "referral_failed",

    EMAIL_VERIFICATION_RESEND: "resend_email_verification",
    EMAIL_VERIFICATION_SUCCESSFUL: "email_verification_successful",
    EMAIL_VERIFICATION_FAILED: "email_verification_failed",

    TRAFFIC_TABLE_VIEWED: "traffic_table_viewed",
    TRAFFIC_TABLE_MODIFIED: "traffic_table_modified",

    APP_LAUNCHED: "app_launched",
    APP_CLOSED: "app_closed",
    APP_NOT_LAUNCHED: "app_not_launched",
    PROXY_SERVER: "proxy_server_started",
    BG_PROCESS: "bg_process_started",

    MANUAL_SETUP_MAC: "manual_setup_mac",

    DARK_MODE_ENABLED: "dark_mode_enabled",
    DARK_MODE_DISABLED: "dark_mode_disabled",
    UPGRADE_REQUIRED_FOR_DARK_MODE: "upgrade_required_for_dark_mode",

    SIMULATE_RULE: "simulate_rule",
    EXECUTION_LOGS: "execution_logs",

    SOURCE_FILTER_FORMAT_UPGRADED: "source_filter_format_upgraded",
    HEADER_RULES_MIGRATED_TO_V2: "header_rules_migrated_to_v2",
    PROMO_BANNER_CLICKED: "promo_banner_clicked",
  },
  ATTR: {
    PAYMENT_MODE: "payment_mode",
    PLANNAME: "planname",
    PLAN_DURATION: "plan_duration",
    PLAN_ID: "plan_id",
    PLAN_START_DATE: "plan_startDate",
    PLAN_END_DATE: "plan_endDate",
    COUPON: "coupon",
    COUPON_VALUE: "coupon_value",
    LICENSE: "licensekey",
    COMPANY: "company",
    REF: "ref",
    COUNTRY: "country",

    DISPLAY_NAME: "display_name",
    PROFILE: "profile",

    NUM_RULES: "NUM_RULES",
    NUM_PREMIUM_ACTIVE_RULES: "num_premium_active_rules",
    NUM_RULE_TYPES: "NUM_RULE_TYPES",
    NUM_RULES_PINNED: "num_rules_pinned",
    NUM_RULE_TYPES_TRIED: "num_rule_types_tried",
    NUM_ACTIVE_RULES: "NUM_ACTIVE_RULES", // TODO: should be in smallcase

    NUM_RULES_EXCLUDING_HEADERS: "num_rules_excluding_headers",
    NUM_ACTIVE_RULES_EXCLUDING_HEADERS: "num_active_rules_excluding_headers",
    NUM_RULES_EXCLUDING_FREE_RULES: "num_rules_excluding_free_rules",
    NUM_ACTIVE_RULES_EXCLUDING_FREE_RULES: "num_active_rules_excluding_free_rules",

    NUM_GROUPS: "NUM_GROUPS",
    NUM_ACTIVE_GROUPS: "NUM_ACTIVE_GROUPS",
    NUM_SHARED_LISTS: "NUM_SHARED_LISTS",
    NUM_FILES: "num_files",
    NUM_MOCKS: "num_mocks",
    NUM_SESSIONS: "num_sessions",
    NUM_SESSIONS_SAVED_ONLINE: "num_sessions_saved_online",
    NUM_SESSIONS_SAVED_OFFLINE: "num_sessions_saved_offline",
    NUM_NETWORK_SESSIONS: "num_network_sessions",
    NUM_LOCAL_WORKSPACES: "num_local_workspaces",

    SESSION_REPLAY_ENABLED: "session_replay_enabled",

    PERSONA: "persona",
    INDUSTRY: "industry",

    SIGNUP_DATE: "SIGNUP_DATE",
    DAYS_SINCE_SIGNUP: "days_since_signup",
    DAYS_SINCE_INSTALL: "days_since_install",

    EXTENSION_INSTALL_DATE: "install_date",
    DESKTOP_INSTALL_DATE: "desktop_install_date",

    APP_MODE: "APP_MODE",
    EMAIL_TYPE: "EMAIL_TYPE",
    EMAIL_DOMAIN: "EMAIL_DOMAIN",
    EMAIL_VERIFIED: "email_verified",
    IS_PREMIUM: "IS_PREMIUM",
    IS_TRIAL: "is_trial",

    NUM_WORKSPACES: "num_workspaces",
    SESSION_REPLAY_LIFETIME_REDEEMED: "session_replay_lifetime_redeemed",
    COMPANY_USER_SERIAL: "company_user_serial",
    APP_FLAVOUR: "app_flavour",
    SESSIONBEAR_INSTALLED: "sessionbear_installed",

    NUM_REQUESTS: "num_requests",
    NUM_COLLECTIONS: "num_collections",
    NUM_ENVIRONMENTS: "num_environments",
    RQ_SUBSCRIPTION_TYPE: "rq_subscription_type",
    SUBSCRIPTION_STATUS: "subscription_status",
    IS_ACCELERATOR_AVAILABLE: "is_accelerator_available",
    BROWSERSTACK_ID: "browserstack_id",
  },
  VALUES: {
    PAYPAL: "paypal",
  },
  GA_CUSTOM_DIMENSIONS: {
    USER_ID: "dimension1",
  },
  GA_CUSTOM_METRICS: {
    num_rules: "metric1",
  },
};
