const AUTH = {};

//ACTION LABELS
AUTH.ACTION_LABELS = {};
AUTH.ACTION_LABELS.LOG_IN = "LOG IN";
AUTH.ACTION_LABELS.SIGN_UP = "SIGN UP";
AUTH.ACTION_LABELS.REQUEST_RESET_PASSWORD = "REQUEST RESET PASSWORD";
AUTH.ACTION_LABELS.DO_RESET_PASSWORD = "DO RESET PASSWORD";

export default AUTH;
