export const CONTENT_TYPE_OPTIONS = [
  { value: "application/json" },
  { value: "application/x-www-form-urlencoded" },
  { value: "application/xhtml+xml" },
  { value: "application/xml" },
  { value: "multipart/form-data" },
  { value: "text/css" },
  { value: "text/csv" },
  { value: "text/plain" },
  { value: "text/html" },
  { value: "text/json" },
  { value: "text/xml" },
];

// took reference from https://www.w3docs.com/learn-html/mime-types.html
export const RESOURCE_TO_CONTENT_TYPES_MAP = {
  html: ["text/html"],
  js: [
    "application/javascript",
    "application/x-javascript",
    "text/javascript",
    "text/x-javascript",
    "application/ecmascript",
  ],
  css: ["text/css"],
  images: [
    "image/gif",
    "image/jpeg",
    "image/jpg",
    "image/pjpeg",
    "image/png",
    "image/svg+xml",
    "image/tiff",
    "image/vnd.microsoft.icon",
    "image/webp",
    "image/x-icon",
    "image/x-jg",
    "image/x-xpixmap",
    "image/x-quicktime",
    "image/x-jps",
    "image/x-pict",
    "image/x-pcx",
    "image/x-windows-bmp",
    "image/bmp",
  ],
  media: [
    "audio/*",
    "audio/basic",
    "audio/midi",
    "audio/mod",
    "audio/mpeg",
    "audio/x-mid",
    "audio/x-midi",
    "audio/x-mpeg-3",
    "audio/x-pn-realaudio",
    "audio/x-wav",
    "video/3gpp",
    "video/3gpp2",
    "video/mp2t",
    "video/mp4",
    "video/mpeg",
    "video/quicktime",
    "video/webm",
    "video/x-flv",
    "video/x-m4v",
    "video/x-matroska",
    "video/x-ms-asf",
    "video/x-msvideo",
    "video/x-ms-wmv",
    "video/x-ms-wmx",
    "video/x-ms-wvx",
    "video/vnd.rn-realvideo",
    "video/vnd.rn-realmedia",
    "video/x-sgi-movie",
  ],
  fonts: [
    "application/vnd.ms-fontobject",
    "application/x-font-opentype",
    "application/x-font-truetype",
    "application/x-font-ttf",
    "application/font-woff",
    "application/font-woff2",
    "application/font-sfnt",
    "application/font-otf",
    "font/woff",
    "font/woff2",
    "font/sfnt",
    "font/ttf",
    "font/otf",
  ],

  others: [
    // this is extendended beyond what is mentioned here
    "application/octet-stream",
    "application/x-mime",
    "application/*",

    // COMMON - DON'T KNOW HOW TO CATEGORIZE THESE
    "text/plain",
    "application/json",
    "text/richtext",
    "application/xml",
    "text/xml",
    "application/x-www-form-urlencoded",
    "application/xhtml+xml",
    "multipart/form-data",
    "text/csv",
  ],
};

export const RESOURCE_TYPE_OPTIONS = Object.keys(RESOURCE_TO_CONTENT_TYPES_MAP).map((resource) => {
  return {
    label: resource,
    value: resource,
  };
});
