const FEATURES = {};

FEATURES.SHARED_LISTS = "shared_lists";
FEATURES.RULES = "rules";
FEATURES.ACTIVE_RULES = "active_rules";
FEATURES.RULE_PAIRS = "rule_pairs";
FEATURES.GROUPS = "groups";
FEATURES.FILES = "files";
FEATURES.EXPORT_IMPORT = "export_import";
FEATURES.EXPORT = "export";
FEATURES.IMPORT = "import";
FEATURES.DARK_MODE = "dark_mode";
FEATURES.BACKUP_RULES = "backup_rules";
FEATURES.SYNCING = "rules_syncing";
FEATURES.ADS = "ads";
FEATURES.LOGS = "logs";
FEATURES.FAV_RULES = "favourite_rules";
FEATURES.RESPONSE_BODY_CHARACTER_LIMIT = "response_body_character_limit";
FEATURES.REQUEST_BODY_CHARACTER_LIMIT = "request_body_character_limit";
FEATURES.SCRIPT_RULE_CHARACTER_LIMIT = "script_rule_character_limit";
FEATURES.TRASH = "trash";
FEATURES.EXECUTION_LOGS = "execution_logs";
FEATURES.CHARACTER_LIMIT = "characters";
FEATURES.RESPONSE_RULE = "response_rule";
FEATURES.REQUEST_RULE = "request_rule";
FEATURES.SCRIPT_RULE = "script_rule";
FEATURES.RESPONSE_MAP_LOCAL = "RESPONSE_MAP_LOCAL";
FEATURES.REDIRECT_MAP_LOCAL = "REDIRECT_MAP_LOCAL";
FEATURES.REQUEST_PAYLOAD_FILTER = "RESPONSE_DATA";
FEATURES.ASYNC_MODIFY_RESPONSE_BODY = "ASYNC_MODIFY_RESPONSE_BODY";
FEATURES.ASYNC_MODIFY_REQUEST_BODY = "ASYNC_MODIFY_REQUEST_BODY";
FEATURES.MODIFY_REQUEST_BODY = "MODIFY_REQUEST_BODY";
FEATURES.UPDATED_REQUEST_BODY_ARGS = "UPDATED_REQUEST_BODY_ARGS";
FEATURES.DESKTOP_APP_TERMINAL_PROXY = "DESKTOP_APP_TERMINAL_PROXY";
FEATURES.DESKTOP_APP_SSL_PROXYING = "DESKTOP_APP_SSL_PROXYING";
FEATURES.DESKTOP_APP_TRAFFIC_TABLE = "DESKTOP_APP_TRAFFIC_TABLE";
FEATURES.EXTENSION_GROUP_PIN_ICON = "EXTENSION_GROUP_PIN_ICON";
FEATURES.EXTENSION_CONSOLE_LOGGER = "EXTENSION_CONSOLE_LOGGER";
FEATURES.FEAT_PRESERVE_REDIRECT_COOKIES = "preserve_redirect_cookies";
FEATURES.ENABLE_TRACKING = "enable_tracking";
FEATURES.REDIRECT_RULE_DEMO_VIDEO_IN_EDITOR = "redirect-rule-tutorial-video-in-editor-experiment";
FEATURES.DESKTOP_USER_PREFERENCES = "desktop_user_preferences";
FEATURES.CREATE_RULE_FROM_TRAFFIC_TABLE = "create-rule-from-traffic-table";
FEATURES.CONNECTED_APPS = "connected-apps";
// MARKETING
FEATURES.INTERCEPTOR = {};
FEATURES.INTERCEPTOR.INTERCEPTOR_LAUNCH = "interceptor-launch";

// RULES
FEATURES.HEADERS_V2_MIGRATION = "headers-v2";
FEATURES.MODIFY_API_RESPONSE_STATUS = "response-rule-modify-status";

FEATURES.MOCK_V2 = "mock-v2";
FEATURES.USERNAME_UPDATE_SUPPORT = "feat-username-update-support";

// WORKSPACES
FEATURES.WORKSPACES = "workspaces";
FEATURES.OPEN_SOURCE_ANNOUNCEMENT = "open_source_announcement";

// PERSONA SURVEY
FEATURES.PERSONA_SURVEY = "persona-survey";

export default FEATURES;
