const STORAGE = {};
STORAGE.LOCAL_STORAGE = {};

STORAGE.LOCAL_STORAGE.REDIRECT_TO_CHROME_STORE_REVIEW = "isRedirectedToChromeStoreReview";
STORAGE.LOCAL_STORAGE.LAST_REMINDER_DATE = "last_reminder_date";
STORAGE.LOCAL_STORAGE.AUTH_REDIRECT_METADATA_KEY = "authRedirectMetadata";
STORAGE.LOCAL_STORAGE.RQ_DESKTOP_APP_AUTH_PARAMS = "rq_desktop_app_auth_params";
STORAGE.LOCAL_STORAGE.CMD_CLICK_MULTI_SELECT_NUDGE_SHOWN = "cmd_click_multi_select_nudge_shown";
export default STORAGE;
