const STORAGE = {};
STORAGE.LOCAL_STORAGE = {};

STORAGE.LOCAL_STORAGE.LAST_REMINDER_DATE = "last_reminder_date";
STORAGE.LOCAL_STORAGE.AUTH_TRIGGER_SOURCE_LOCAL_KEY = "authTriggerSource";
STORAGE.LOCAL_STORAGE.RQ_DESKTOP_APP_AUTH_PARAMS = "rq_desktop_app_auth_params";

export default STORAGE;
