import React, { useCallback } from "react";
import { EnvironmentVariables } from "backend/environment/types";
import { useGraphQLRecordStore } from "features/apiClient/hooks/useGraphQLRecordStore";
import AuthorizationView from "../../../../../components/request/components/AuthorizationView";
import { resolveAuth } from "features/apiClient/screens/apiClient/utils";
import { useAPIRecords } from "features/apiClient/store/apiRecords/ApiRecordsContextProvider";
import {
  AutogeneratedFieldsNamespace,
  parseAuth,
  SimpleKeyValuePair,
} from "features/apiClient/store/autogenerateStore";
import useEnvironmentManager from "backend/environment/hooks/useEnvironmentManager";
import { RQAPI } from "features/apiClient/types";
import { useAutogenerateStore } from "features/apiClient/hooks/useAutogenerateStore";

interface Props {
  variables: EnvironmentVariables;
}

export const GraphQLAuthView: React.FC<Props> = ({ variables }) => {
  const [recordId, collectionId, auth, updateAuth] = useGraphQLRecordStore((state) => [
    state.record.id,
    state.record.collectionId,
    state.record.data.auth,
    state.updateRecordAuth,
  ]);
  const { renderVariables } = useEnvironmentManager();
  const [getData, getParentChain] = useAPIRecords((state) => [state.getData, state.getParentChain]);
  const [purgeAndAdd] = useAutogenerateStore((state) => [state.purgeAndAdd, state.purgeAndAddHeaders]);

  const resolver = useCallback(
    <T extends Record<string, any>>(template: T) => {
      return renderVariables(template, collectionId).result;
    },
    [renderVariables, collectionId]
  );

  const handleAuthUpdate = useCallback(
    (newAuth: RQAPI.Auth) => {
      const childDetails = {
        id: recordId,
        parentId: collectionId,
      };

      const resolvedAuth = resolveAuth(newAuth, childDetails, getParentChain, getData);
      const { headers, queryParams } = parseAuth(resolvedAuth, resolver);
      const headersContent = Object.fromEntries(headers);

      const queryParamsContent: SimpleKeyValuePair[] = [];
      queryParams.forEach(({ key, value }) => {
        queryParamsContent.push({ key, value });
      });
      purgeAndAdd(AutogeneratedFieldsNamespace.AUTH, headersContent, queryParamsContent);
      updateAuth(newAuth);
    },
    [purgeAndAdd, updateAuth, recordId, collectionId, getParentChain, getData, resolver]
  );

  return (
    <div className="graphql-request-tab-content" style={{ height: "inherit" }}>
      <AuthorizationView
        defaults={auth}
        onAuthUpdate={handleAuthUpdate}
        isRootLevelRecord={!collectionId}
        variables={variables}
      />
    </div>
  );
};
