export const actions = {
  REQUEST_INVOICE: "REQUEST_INVOICE",
  UPDATE_PAYMENT_METHOD: "UPDATE_PAYMENT_METHOD",
  ADD_REMOVE_TEAM_USERS: "ADD_REMOVE_TEAM_USERS",
  CHANGE_BILLING_CYCLE: "CHANGE_BILLING_CYCLE",
  MIGRATE_SUBSCRIPTION: "MIGRATE_SUBSCRIPTION",
  CANCEL_SUBSCRIPTION: "CANCEL_SUBSCRIPTION",
};
