export const SESSIONS = {
  DRAFT_SESSION_RECORDING_VIEWED: "draft_session_recording_viewed",
  DRAFT_SESSION_DISCARDED: "draft_session_discarded",
  DRAFT_SESSION_RECORDING_NAMED: "draft_session_recording_named",
  SESSION_RECORDING_FAILED: "session_recording_failed",
  DRAFT_SESSION_RECORDING_SAVED: "draft_session_recording_saved",
  DRAFT_SESSION_RECORDING_SAVE_FAILED: "draft_session_recording_save_failed",
  SAVED_SESSION_RECORDING_VIEWED: "saved_session_recording_viewed",
  SESSION_RECORDING_SHARE_CLICKED: "session_recording_share_clicked",
  SESSION_RECORDING_SHARE_LINK_COPIED: "session_recording_share_link_copied",
  SESSION_RECORDING_VISIBILITY_UPDATED: "session_recording_visibility_updated",
  SESSION_RECORDING_DELETED: "session_recording_deleted",
  SESSION_RECORDING_DESCRIPTION_ADDED: "session_recording_description_added",
  SESSION_RECORDING_NAME_UPDATED: "session_recording_name_updated",
  BAD_SESSION_RECORDING_VIEWED: "bad_session_recording_viewed",
  SESSION_RECORDING_BOTTOM_SHEET_TAB_CLICKED: "session_recording_bottom_sheet_tab_clicked",
};
