import { createSelector } from "@reduxjs/toolkit";
import lodash from 'lodash';
import { selectAncestorRecords, selectRecordById } from "../apiRecords";
import { ApiClientStoreState } from "../workspaceView/helpers/ApiClientContextRegistry";
import { Authorization } from "features/apiClient/screens/apiClient/components/views/components/request/components/AuthorizationView/types/AuthConfig";
import { NativeError } from "errors/NativeError";
import { EntityNotFound } from "../types";
import { useApiClientSelector } from "../hooks/base.hooks";
import { ScopedVariables, useScopedVariables } from "features/apiClient/helpers/variableResolver/variable-resolver";
import { renderTemplate } from "backend/environment/utils";
import { RQAPI } from "features/apiClient/types";
import { extractAuthHeadersAndParams } from "features/apiClient/helpers/auth";

function makeAuthChainSelector(id: string) {
  const selector = createSelector(
    [
      (state: ApiClientStoreState) => ({
        self: selectRecordById(state, id),
        parents: selectAncestorRecords(state, id),
      })
    ],
    ({ self, parents }) => {
      if (!self) {
        throw new EntityNotFound(id, 'record');
      }
      return [self, ...parents].map(p => p.data.auth)
    },
  );

  return selector;
}

function makeAuthResolverSelector(id: string) {
  const selector = createSelector(
    [
      makeAuthChainSelector(id),
    ],
    (authChain) => {
      for (const auth of authChain) {
        if (auth.currentAuthType !== Authorization.Type.INHERIT) {
          return auth as RQAPI.Auth & { currentAuthType: Exclude<Authorization.Type, Authorization.Type.INHERIT>};
        }
      }

      throw new NativeError(`Could not find auth of ${id}, neither in self, nor in parent chain!`);
    },
  );

  return selector;
}

function makeFilledAuthSelector(id: string, scopedVariables: ScopedVariables) {
  const selector = createSelector(
    [makeAuthResolverSelector(id)],
    (auth) => {
      if(auth.currentAuthType === Authorization.Type.NO_AUTH) {
        return auth;
      }
      const { renderedTemplate } = renderTemplate(auth as any, lodash.mapValues(scopedVariables, ([v]) => v));
      return renderedTemplate as RQAPI.Auth;
    },
  );

  return selector;
}

function makeAutoGeneratedFieldsSelector(id: string, scopedVariables: ScopedVariables) {
  const selector = createSelector(
    [makeFilledAuthSelector(id,scopedVariables)],
    (auth) => extractAuthHeadersAndParams(auth)
  );

  return selector;
}

export function useAutoGeneratedFields(id: string) {
  const scopedVariables = useScopedVariables(id);
  return useApiClientSelector(makeAutoGeneratedFieldsSelector(id, scopedVariables))
}
