import { createSelector } from "@reduxjs/toolkit";
import lodash from "lodash";
import { selectAncestorRecords, selectRecordById } from "../apiRecords";
import { ApiClientStoreState } from "../workspaceView/helpers/ApiClientContextRegistry";
import { Authorization } from "features/apiClient/screens/apiClient/components/views/components/request/components/AuthorizationView/types/AuthConfig";
import { InvalidEntityShape } from "../types";
import { useApiClientSelector } from "../hooks/base.hooks";
import { ScopedVariables, useScopedVariables } from "features/apiClient/helpers/variableResolver/variable-resolver";
import { renderTemplate } from "backend/environment/utils";
import { RequestContentType, RQAPI } from "features/apiClient/types";
import { extractAuthHeadersAndParams } from "features/apiClient/helpers/auth";
import { isGraphQLApiEntry } from "features/apiClient/screens/apiClient/utils";
import { createHeaderEntry } from "features/apiClient/store/autogenerateStore";
import { CONTENT_TYPE_HEADER } from "features/apiClient/constants";
import { ApiClientEntity, HttpRecordEntity } from "../entities";
import { BufferedApiClientEntity } from "../entities/buffered/factory";

function makeAuthChainSelector(id: string) {
  const selector = createSelector(
    [
      (state: ApiClientStoreState) => ({
        self: selectRecordById(state, id),
        parents: selectAncestorRecords(state, id),
      }),
    ],
    ({ self, parents }) => {
      if (!self) {
        return parents.map((p) => p.data.auth);
      }
      return [self, ...parents].map((p) => p.data.auth);
    }
  );

  return selector;
}

export function makeAuthResolverSelector(id: string) {
  const selector = createSelector([makeAuthChainSelector(id)], (authChain) => {
    for (const auth of authChain) {
      if (auth.currentAuthType !== Authorization.Type.INHERIT) {
        return auth as RQAPI.Auth & { currentAuthType: Exclude<Authorization.Type, Authorization.Type.INHERIT> };
      }
    }

    return {
      currentAuthType: Authorization.Type.NO_AUTH,
      authConfigStore: {},
    } as RQAPI.Auth;
  });

  return selector;
}

function makeFilledAuthSelector(id: string, scopedVariables: ScopedVariables) {
  const selector = createSelector([makeAuthResolverSelector(id)], (auth) => {
    if (auth.currentAuthType === Authorization.Type.NO_AUTH) {
      return auth;
    }
    const { renderedTemplate } = renderTemplate(
      auth as any,
      lodash.mapValues(scopedVariables, ([v]) => v)
    );
    return renderedTemplate as RQAPI.Auth;
  });

  return selector;
}

function makeContentTypeSelector(entity: HttpRecordEntity) {
  const selector = createSelector(
    [
      (state: ApiClientStoreState) => entity.getEntityFromState(state),
    ],
    (record) => {
      if(record.type !== RQAPI.RecordType.API) {
        throw new InvalidEntityShape({
          id: record.id,
          expectedType: 'record',
          foundType: record.type,
        });
      }
      const entry = record.data;
      if(isGraphQLApiEntry(entry)) {
        return createHeaderEntry(CONTENT_TYPE_HEADER, RequestContentType.JSON)
      }
      if(entry.request.body && entry.request.body.length > 0 && entry.request.contentType) {
        return createHeaderEntry(CONTENT_TYPE_HEADER, entry.request.contentType);
      }
    }
  );

  return selector;
}

export function makeAutoGeneratedFieldsSelector(id: string, scopedVariables: ScopedVariables, entity: HttpRecordEntity) {
  const selector = createSelector(
    [makeFilledAuthSelector(id, scopedVariables), makeContentTypeSelector(entity)],
    (auth, contentTypeHeader) => {
      const result = extractAuthHeadersAndParams(auth);
      if(contentTypeHeader) {
        result.headers.push({
          id: result.headers.length + 1,
          isEnabled: true,
          key: CONTENT_TYPE_HEADER,
          value: contentTypeHeader.value
        });
      }

      return result;
    }
  );

  return selector;
}

export function useAutoGeneratedFields(entity: HttpRecordEntity) {
  const id = (() => {
    const referenceId = (entity as unknown as BufferedApiClientEntity).meta.referenceId;
    if(referenceId) {
      return referenceId;
    }

    return entity.id;
  })();
  const scopedVariables = useScopedVariables(id);
  return useApiClientSelector(makeAutoGeneratedFieldsSelector(id, scopedVariables, entity));
}
