const RULE_EDITOR_CONFIG = {};
RULE_EDITOR_CONFIG.MODES = {};

RULE_EDITOR_CONFIG.MODES.CREATE = "create";
RULE_EDITOR_CONFIG.MODES.EDIT = "edit";
RULE_EDITOR_CONFIG.MODES.SHARED_LIST_RULE_VIEW = "shared-list-rule-view";

export default RULE_EDITOR_CONFIG;
