const THEME_COLORS = {
  PRIMARY_COLOR: "#0a48b3",
  BTN_BGCOLOR_PRIMARY: "#f8f9fa",
  BTN_FONT_COLOR_PRIMARY: "#393f49",
  BTN_FONT_COLOR_HOVER: "#FFFFFF",
  BTN_COLOR_IN_ROW: "#465e74",
  ICON_COLOR_ON_HOVER: "#525f7f",
};

export default THEME_COLORS;
