import React, { useCallback } from "react";
import { EnvironmentVariables } from "backend/environment/types";
import { KeyValuePair, RQAPI } from "features/apiClient/types";
import { KeyValueTable } from "../../../KeyValueTable/KeyValueTable";
import { useAutogenerateStore } from "features/apiClient/hooks/useAutogenerateStore";
import { AutoGeneratedTable } from "../../../KeyValueTable/AutoGeneratedTable";

interface HeadersTableProps {
  headers: KeyValuePair[];
  variables: EnvironmentVariables;
  setRequestEntry: (updaterFn: (prev: RQAPI.Entry) => RQAPI.Entry) => void;
}

export const HeadersTable: React.FC<HeadersTableProps> = ({ headers, variables, setRequestEntry }) => {
  const [v, getAllHeaders] = useAutogenerateStore((s) => [s.headerVersion, s.getAllHeaders]);

  console.log(v);

  const autogeneratedHeaders = getAllHeaders();

  const handleHeadersChange = useCallback(
    (updatedHeaders: KeyValuePair[]) => {
      setRequestEntry((prev) => ({
        ...prev,
        request: {
          ...prev.request,
          headers: updatedHeaders,
        },
      }));
    },
    [setRequestEntry]
  );

  return (
    <div>
      {autogeneratedHeaders.length > 0 && <AutoGeneratedTable data={autogeneratedHeaders} type="headers" />}
      <KeyValueTable data={headers} variables={variables} onChange={handleHeadersChange} checkInvalidCharacter={true} />
    </div>
  );
};
