export const TAB_EVENTS = {
  TAB_OPEN_CLICKED: "TAB_OPEN_CLICKED",
  TAB_OPENED: "TAB_OPENED",
  TAB_CLOSE_CLICKED: "TAB_CLOSE_CLICKED",
  TAB_CLOSED: "TAB_CLOSED",
  RESET_TAB_SERVICE_STORE: "RESET_TAB_SERVICE_STORE",
  TABS_REHYDRATION_STARTED: "TABS_REHYDRATION_STARTED",
  TABS_REHYDRATION_COMPLETED: "TABS_REHYDRATION_COMPLETED",
  TABS_LOCAL_STORAGE_SET_ITEM_CALLED: "TABS_LOCAL_STORAGE_SET_ITEM_CALLED",
  TABS_LOCAL_STORAGE_GET_ITEM_CALLED: "TABS_LOCAL_STORAGE_GET_ITEM_CALLED",
  TAB_GENERIC_STATE_SET_TITLE: "TAB_GENERIC_STATE_SET_TITLE",
  TAB_GENERIC_STATE_SET_PREVIEW_MODE: "TAB_GENERIC_STATE_SET_PREVIEW_MODE",
  TAB_GENERIC_STATE_SET_SAVED: "TAB_GENERIC_STATE_SET_SAVED",
};
