export const TAB_EVENTS = {
  TAB_OPEN_CLICKED: "TAB_OPEN_CLICKED",
  TAB_OPENED: "TAB_OPENED",

  UPSERT_TAB_SOURCE_CALLED: "UPSERT_TAB_SOURCE_CALLED",
  UPSERT_TAB_SOURCE_COMPLETED: "UPSERT_TAB_SOURCE_COMPLETED",

  TAB_CLOSE_CLICKED: "TAB_CLOSE_CLICKED",
  TAB_CLOSED: "TAB_CLOSED",

  TAB_CLOSE_BY_ID: "TAB_CLOSE_BY_ID",
  TAB_CLOSED_BY_ID: "TAB_CLOSED_BY_ID",

  TAB_ACTION_EARLY_RETURN: "TAB_ACTION_EARLY_RETURN",

  RESET_TAB_SERVICE_STORE: "RESET_TAB_SERVICE_STORE",

  TABS_REHYDRATION_STARTED: "TABS_REHYDRATION_STARTED",
  TABS_REHYDRATION_ERROR: "TABS_REHYDRATION_ERROR",
  TABS_REHYDRATION_COMPLETED: "TABS_REHYDRATION_COMPLETED",

  TABS_LOCAL_STORAGE_SET_ITEM_CALLED: "TABS_LOCAL_STORAGE_SET_ITEM_CALLED",
  TABS_LOCAL_STORAGE_GET_ITEM_CALLED: "TABS_LOCAL_STORAGE_GET_ITEM_CALLED",

  TAB_GENERIC_STATE_SET_TITLE: "TAB_GENERIC_STATE_SET_TITLE",
  TAB_GENERIC_STATE_SET_PREVIEW_MODE: "TAB_GENERIC_STATE_SET_PREVIEW_MODE",
  TAB_GENERIC_STATE_SET_UNSAVED: "TAB_GENERIC_STATE_SET_UNSAVED",
};
