import React, { useCallback } from "react";
import AuthorizationView from "../../../../../components/request/components/AuthorizationView";
import { resolveAuth } from "features/apiClient/screens/apiClient/utils";
import {
  AutogeneratedFieldsNamespace,
  parseAuth,
  SimpleKeyValuePair,
} from "features/apiClient/store/autogenerateStore";
import { useAutogenerateStore } from "features/apiClient/hooks/useAutogenerateStore";
import { renderTemplate } from "backend/environment/utils";
import { BufferedGraphQLRecordEntity } from "features/apiClient/slices/entities";
import { useApiClientSelector } from "features/apiClient/slices/hooks/base.hooks";
import { useApiClientStore } from "features/apiClient/slices/workspaceView/helpers/ApiClientContextRegistry/hooks";
import { selectAncestorIds, selectRecordById } from "features/apiClient/slices/apiRecords";
import { useScopedVariables } from "features/apiClient/helpers/variableResolver/variable-resolver";

interface Props {
  entity: BufferedGraphQLRecordEntity;
}

export const GraphQLAuthView: React.FC<Props> = ({ entity }) => {
  const auth = useApiClientSelector((s) => entity.getAuth(s));
  const collectionId = useApiClientSelector((s) => entity.getCollectionId(s));
  const recordId = entity.meta.referenceId || entity.id;
  const [purgeAndAdd] = useAutogenerateStore((state) => [state.purgeAndAdd]);
  const scopedVariables = useScopedVariables(recordId);
  const store = useApiClientStore();

  const getParentChain = useCallback(
    (id: string) => {
      const state = store.getState();
      return selectAncestorIds(state, id);
    },
    [store]
  );

  const getData = useCallback(
    (id: string | undefined) => {
      if (!id) return undefined;
      const state = store.getState();
      return selectRecordById(state, id) || undefined;
    },
    [store]
  );

  const resolver = useCallback(
    <T extends Record<string, any>>(template: T) => {
      const { renderedTemplate } = renderTemplate(
        template,
        Object.fromEntries(Object.entries(scopedVariables).map(([k, [v]]) => [k, v]))
      );
      return renderedTemplate;
    },
    [scopedVariables]
  );

  const handleAuthUpdate = useCallback(
    (newAuth: any) => {
      const childDetails = {
        id: recordId,
        parentId: collectionId || undefined,
      };

      const resolvedAuth = resolveAuth(newAuth, childDetails, getParentChain, getData);
      const { headers, queryParams } = parseAuth(resolvedAuth, resolver);
      const headersContent = Object.fromEntries(headers);

      const queryParamsContent: SimpleKeyValuePair[] = [];
      queryParams.forEach(({ key, value }) => {
        queryParamsContent.push({ key, value });
      });
      purgeAndAdd(AutogeneratedFieldsNamespace.AUTH, headersContent, queryParamsContent);
      entity.setAuth(newAuth);
    },
    [purgeAndAdd, entity, collectionId, getParentChain, getData, resolver, recordId]
  );

  return (
    <div className="graphql-request-tab-content" style={{ height: "inherit" }}>
      <AuthorizationView
        defaults={auth}
        onAuthUpdate={handleAuthUpdate}
        isRootLevelRecord={!collectionId}
        recordId={entity.meta.referenceId}
      />
    </div>
  );
};
