import { RQAPI } from "features/apiClient/types";

export const requests = [
  { id: "1", name: "Invite user", data: { request: { method: "GET" } } },
  { id: "2", name: "Delete user invite", data: { request: { method: "DELETE" } } },
  {
    id: "3",
    name: "Add new user invite Add new user invite Add new user invite",
    data: { request: { method: "POST" } },
  },
  {
    id: "4",
    name: "Add new user invite Add new user invite Add new user invite",
    data: { request: { method: "POST" } },
  },
  { id: "5", name: "Delete user invite", data: { request: { method: "DELETE" } } },
  {
    id: "6",
    name:
      "Add new user invite Add new user invite Add new user invite Add new user invite Add new user invite Add new user invite ",
    data: { request: { method: "POST" } },
  },
  {
    id: "7",
    name: "Add new user invite Add new user invite Add new user invite",
    data: { request: { method: "POST" } },
  },
  { id: "8", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "9", name: "Update user invite", data: { request: { method: "PUT" } } },

  { id: "11", name: "Invite user", data: { request: { method: "GET" } } },
  { id: "21", name: "Delete user invite", data: { request: { method: "DELETE" } } },
  {
    id: "31",
    name: "Add new user invite Add new user invite Add new user invite",
    data: { request: { method: "POST" } },
  },
  {
    id: "41",
    name: "Add new user invite Add new user invite Add new user invite",
    data: { request: { method: "POST" } },
  },
  { id: "51", name: "Delete user invite", data: { request: { method: "DELETE" } } },
  {
    id: "61",
    name: "Add new user invite Add new user invite Add new user invite",
    data: { request: { method: "POST" } },
  },
  {
    id: "71",
    name: "Add new user invite Add new user invite Add new user invite",
    data: { request: { method: "POST" } },
  },
  { id: "81", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "91", name: "Update user invite", data: { request: { method: "PUT" } } },

  { id: "112", name: "Invite user", data: { request: { method: "GET" } } },
  { id: "212", name: "Delete user invite", data: { request: { method: "DELETE" } } },
  {
    id: "312",
    name: "Add new user invite Add new user invite Add new user invite",
    data: { request: { method: "POST" } },
  },
  {
    id: "412",
    name: "Add new user invite Add new user invite Add new user invite",
    data: { request: { method: "POST" } },
  },
  { id: "512", name: "Delete user invite", data: { request: { method: "DELETE" } } },
  {
    id: "612",
    name: "Add new user invite Add new user invite Add new user invite",
    data: { request: { method: "POST" } },
  },
  {
    id: "712",
    name: "Add new user invite Add new user invite Add new user invite",
    data: { request: { method: "POST" } },
  },
  { id: "812", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "912", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "812", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "912", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "812", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "912", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "812", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "912", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "812", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "912", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "812", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "912", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "812", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "912", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "812", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "912", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "812", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "912", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "812", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "912", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "812", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "912", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "812", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "912", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "812", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "912", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "812", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "912", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "812", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "912", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "812", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "912", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "812", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "912", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "812", name: "Update user invite", data: { request: { method: "PUT" } } },
  { id: "912", name: "Update user invite", data: { request: { method: "PUT" } } },
] as RQAPI.ApiRecord[];
