import { useGraphQLRecordStore } from "features/apiClient/hooks/useGraphQLRecordStore";
import { RQAPI } from "features/apiClient/types";
import GraphQLClientUrl from "./components/GraphQLClientUrl/GraphQLClientUrl";
import React, { useCallback, useContext, useEffect, useLayoutEffect, useMemo, useRef, useState } from "react";
import useEnvironmentManager from "backend/environment/hooks/useEnvironmentManager";
import { RQButton } from "lib/design-system-v2/components";
import { useApiClientContext } from "features/apiClient/contexts";
import { toast } from "utils/Toast";
import { useSelector } from "react-redux";
import { getAppMode } from "store/selectors";
import { AutogenerateStoreContext } from "features/apiClient/store/autogenerateContextProvider";
import { GraphQLRequestExecutor } from "features/apiClient/helpers/graphQLRequestExecutor/GraphQLRequestExecutor";
import { useGraphQLIntrospection } from "features/apiClient/hooks/useGraphQLIntrospection";
import { useDebounce } from "hooks/useDebounce";
import { RBACButton, RevertViewModeChangesAlert, RoleBasedComponent } from "features/rbac";
import { Conditional } from "components/common/Conditional";
import { getUserAuthDetails } from "store/slices/global/user/selectors";
import { Space } from "antd";
import { ApiClientBreadCrumb } from "../components/ApiClientBreadCrumb/ApiClientBreadCrumb";
import { KEYBOARD_SHORTCUTS } from "../../../../../../../constants/keyboardShortcuts";
import { useGenericState } from "hooks/useGenericState";
import { BottomSheetLayout, useBottomSheetContext } from "componentsV2/BottomSheet";
import { BottomSheetPlacement, SheetLayout } from "componentsV2/BottomSheet/types";
import { GraphQLRequestTabs } from "./components/GraphQLRequestTabs/GraphQLRequestTabs";
import { ApiClientBottomSheet } from "../components/response/ApiClientBottomSheet/ApiClientBottomSheet";
import { ClientCodeButton } from "../components/ClientCodeButton/ClientCodeButton";
import "./gqClientView.scss";
import { GraphQLRecordProvider } from "features/apiClient/store/apiRecord/graphqlRecord/GraphQLRecordContextProvider";

interface Props {
  notifyApiRequestFinished: (entry: RQAPI.GraphQLApiEntry) => void;
  onSaveCallback: (apiEntryDetails: RQAPI.GraphQLApiRecord) => void;
  isCreateMode: boolean;
  openInModal?: boolean;
}

const GraphQLClientView: React.FC<Props> = ({
  notifyApiRequestFinished,
  onSaveCallback,
  isCreateMode,
  openInModal = false,
}) => {
  const [
    recordId,
    url,
    collectionId,
    response,
    hasUnsavedChanges,
    updateRecordRequest,
    updateRecord,
    getRecord,
    getRecordName,
    updateRecordResponse,
    setHasUnsavedChanges,
  ] = useGraphQLRecordStore((state) => [
    state.record.id,
    state.record.data.request.url,
    state.record.collectionId,
    state.record.data.response,
    state.hasUnsavedChanges,
    state.updateRecordRequest,
    state.updateRecord,
    state.getRecord,
    state.getRecordName,
    state.updateRecordResponse,
    state.setHasUnsavedChanges,
  ]);

  const { apiClientRecordsRepository, onSaveRecord, apiClientWorkloadManager } = useApiClientContext();
  const { sheetPlacement, toggleSheetPlacement } = useBottomSheetContext();
  const {
    getVariablesWithPrecedence,
    getCurrentEnvironmentVariables,
    getCollectionVariables,
    getGlobalVariables,
    getCurrentEnvironment,
    setVariables,
    setCollectionVariables,
    renderVariables,
    environmentSyncRepository,
  } = useEnvironmentManager();

  const user = useSelector(getUserAuthDetails);
  const appMode = useSelector(getAppMode);

  const { getIsActive, setUnsaved } = useGenericState();

  const enableHotkey = getIsActive();

  const [isSaving, setIsSaving] = useState(false);
  const [isSending, setIsSending] = useState(false);
  const [graphQLRequestExecutor, setGraphQLRequestExecutor] = useState<GraphQLRequestExecutor | null>(null);
  const autoGeneratedStore = useContext(AutogenerateStoreContext);
  const [error] = useState<RQAPI.ExecutionError | undefined>(undefined);
  const [warning] = useState<RQAPI.ExecutionWarning | undefined>(undefined);

  const originalRecord = useRef(getRecord().data);

  const currentEnvironmentVariables = useMemo(() => getVariablesWithPrecedence(collectionId), [
    collectionId,
    getVariablesWithPrecedence,
  ]);

  const handleUrlChange = useCallback(
    (value: string) => {
      updateRecordRequest({
        url: value,
      });
    },
    [updateRecordRequest]
  );

  const {
    introspectAndSaveSchema,
    isIntrospectionDataFetchingFailed,
    fetchingIntrospectionData,
  } = useGraphQLIntrospection();

  const debouncedIntrospection = useDebounce(introspectAndSaveSchema, 500);

  useEffect(() => {
    if (url) {
      debouncedIntrospection();
    }
  }, [url, debouncedIntrospection]);

  const handleUrlInputEnterPressed = useCallback((evt: KeyboardEvent) => {
    (evt.target as HTMLInputElement).blur();
  }, []);

  const handleSave = useCallback(async () => {
    const apiRecord = getRecord();

    const recordToSave: Partial<RQAPI.ApiRecord> = {
      type: RQAPI.RecordType.API,
      data: {
        ...apiRecord.data,
      },
    };
    if (isCreateMode) {
      const requestId = apiClientRecordsRepository.generateApiRecordId();
      recordToSave.id = requestId;
    }

    if (apiRecord?.id) {
      recordToSave.id = apiRecord?.id;
    }
    setIsSaving(true);
    const result = isCreateMode
      ? await apiClientRecordsRepository.createRecordWithId(recordToSave, recordToSave.id)
      : await apiClientRecordsRepository.updateRecord(recordToSave, recordToSave.id);

    if (result.success && result.data.type === RQAPI.RecordType.API) {
      onSaveRecord({ ...(apiRecord ?? {}), ...result.data, data: { ...result.data.data, ...recordToSave.data } });
      onSaveCallback(result.data as RQAPI.GraphQLApiRecord);
      setHasUnsavedChanges(false);
      toast.success("Request saved!");
    } else {
      toast.error("Something went wrong while saving the request");
    }
    setIsSaving(false);
  }, [onSaveCallback, getRecord, isCreateMode, apiClientRecordsRepository, onSaveRecord, setHasUnsavedChanges]);

  const handleRevertChanges = () => {
    updateRecord(originalRecord.current);
  };

  const handleSend = useCallback(async () => {
    const record = getRecord();
    try {
      if (!record) {
        throw new Error("Record not found");
      }

      setIsSending(true);
      const apiClientExecutionResult = await graphQLRequestExecutor.executeGraphQLRequest(record);

      const entryWithResponse = apiClientExecutionResult.executedEntry as RQAPI.GraphQLApiEntry;
      updateRecordResponse(entryWithResponse.response);

      toast.success("Request executed successfully");
    } catch (error) {
      toast.error("Something went wrong while sending the request");
    } finally {
      setIsSending(false);
    }
  }, [graphQLRequestExecutor, getRecord, updateRecordResponse]);

  const handleUpdatesFromExecutionWorker = useCallback(
    async (state: any) => {
      for (const key in state) {
        if (key === "environment") {
          const currentEnvironment = getCurrentEnvironment() as {
            currentEnvironmentName?: string;
            currentEnvironmentId?: string;
          };
          if (currentEnvironment.currentEnvironmentId) {
            await setVariables(currentEnvironment.currentEnvironmentId, state[key]);
          }
        }
        if (key === "global") {
          const globalEnvId = environmentSyncRepository.getGlobalEnvironmentId();
          await setVariables(globalEnvId, state[key]);
        }
        if (key === "collectionVariables") {
          await setCollectionVariables(state[key], collectionId);
        }
      }
    },
    [getCurrentEnvironment, setVariables, setCollectionVariables, collectionId, environmentSyncRepository]
  );

  useEffect(() => {
    if (graphQLRequestExecutor) {
      graphQLRequestExecutor.updateInternalFunctions({
        getCollectionVariables,
        getEnvironmentVariables: getCurrentEnvironmentVariables,
        getGlobalVariables,
        postScriptExecutionCallback: handleUpdatesFromExecutionWorker,
        renderVariables,
      });
    }
  }, [
    getCurrentEnvironmentVariables,
    getCollectionVariables,
    getGlobalVariables,
    handleUpdatesFromExecutionWorker,
    graphQLRequestExecutor,
    renderVariables,
  ]);

  useEffect(() => {
    setUnsaved(hasUnsavedChanges);
  }, [hasUnsavedChanges, setUnsaved]);

  useEffect(() => {
    if (!graphQLRequestExecutor) {
      setGraphQLRequestExecutor(new GraphQLRequestExecutor(appMode, apiClientWorkloadManager, autoGeneratedStore));
    }
  }, [apiClientWorkloadManager, appMode, graphQLRequestExecutor, autoGeneratedStore]);
  const isDefaultPlacementRef = useRef(false);
  useLayoutEffect(() => {
    if (isDefaultPlacementRef.current) {
      return;
    }

    isDefaultPlacementRef.current = true;
    const bottomSheetPlacement = window.innerWidth < 1600 ? BottomSheetPlacement.BOTTOM : BottomSheetPlacement.RIGHT;
    toggleSheetPlacement(bottomSheetPlacement);
  }, [toggleSheetPlacement]);

  return (
    <div className="api-client-view gql-client-view">
      <div className="api-client-header-container">
        <RoleBasedComponent
          permission="create"
          resource="api_client_request"
          fallback={
            <Conditional condition={user.loggedIn && !openInModal && hasUnsavedChanges}>
              <RevertViewModeChangesAlert
                title="As a viewer, You can modify and test APIs, but cannot save updates."
                callback={handleRevertChanges}
              />
            </Conditional>
          }
        />
        <div className="api-client-header-container__header">
          <div className="api-client-breadcrumb-container">
            <ApiClientBreadCrumb
              openInModal={openInModal}
              name={getRecordName()}
              OnRecordNameUpdate={() => {}}
              onBlur={() => {}}
            />

            <ClientCodeButton apiClientExecutor={graphQLRequestExecutor} />
          </div>

          <div className="api-client-header__url">
            <Space.Compact className="api-client-url-container">
              <GraphQLClientUrl
                url={url}
                currentEnvironmentVariables={currentEnvironmentVariables}
                onEnterPress={handleUrlInputEnterPressed}
                onUrlChange={handleUrlChange}
                fetchingIntrospectionData={fetchingIntrospectionData}
                isIntrospectionDataFetchingFailed={isIntrospectionDataFetchingFailed}
              />
            </Space.Compact>
            <RQButton
              showHotKeyText
              onClick={() => handleSend()}
              hotKey={KEYBOARD_SHORTCUTS.API_CLIENT.SEND_REQUEST.hotKey}
              type="primary"
              className="text-bold"
              disabled={!url}
              loading={isSending}
            >
              Send
            </RQButton>

            <Conditional condition={!openInModal}>
              <RBACButton
                disabled={!hasUnsavedChanges}
                permission="create"
                resource="api_client_request"
                showHotKeyText
                hotKey={KEYBOARD_SHORTCUTS.API_CLIENT.SAVE_REQUEST.hotKey}
                onClick={handleSave}
                loading={isSaving}
                tooltipTitle="Saving is not allowed in view-only mode. You can update and view changes but cannot save them."
                enableHotKey={enableHotkey}
              >
                Save
              </RBACButton>
            </Conditional>
          </div>
        </div>
      </div>
      {/* TODO: update props when integrating execution adapter */}
      <BottomSheetLayout
        layout={SheetLayout.SPLIT}
        bottomSheet={
          <ApiClientBottomSheet
            key={recordId}
            response={response}
            testResults={[]}
            isLoading={false}
            isFailed={false}
            isRequestCancelled={false}
            onCancelRequest={() => {}}
            handleTestResultRefresh={() => Promise.resolve()}
            error={error}
            onDismissError={() => {}}
            warning={warning}
            executeRequest={() => Promise.resolve()}
          />
        }
        minSize={sheetPlacement === BottomSheetPlacement.BOTTOM ? 25 : 350}
        initialSizes={sheetPlacement === BottomSheetPlacement.BOTTOM ? [60, 40] : [60, 40]}
      >
        <div className="api-client-body">
          <GraphQLRequestTabs requestId={recordId} variables={currentEnvironmentVariables} />
        </div>
      </BottomSheetLayout>
    </div>
  );
};

const WithGraphQLRecordProvider = (Component: React.ComponentType<any>) => {
  return (props: any) => {
    return (
      <GraphQLRecordProvider record={props.selectedEntryDetails}>
        <Component {...props} />
      </GraphQLRecordProvider>
    );
  };
};

export default WithGraphQLRecordProvider(GraphQLClientView);
